version: '3'
services:
  db-mongo:
    image: mvertes/alpine-mongo:latest
    networks:
      - back-tier
    volumes:
      - db-data:/data/db
  backend:
    build: .
    command: nodemon . --exitcrash
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    ports:
      - "3003:3000"
    links:
      - db-mongo
    environment:
      - PORT=3000
      - NODE_ENV=development
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
volumes:
  dependencies:
  db-data: