version: '3'
services:
  db-mongo:
    image: mvertes/alpine-mongo:latest
    networks:
      - back-tier
    volumes:
      - db-data:/data/db
  redis:
    image: redis
    networks:
      - back-tier
    volumes:
      - db-data:/data/re-db
  backend:
    build: .
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    ports:
      - "3000:8080"
    links:
      - db-mongo
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGO_HOST=db-mongo
      - REDIS_HOST=redis
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
volumes:
  dependencies:
  db-data: